version: '2'

services:
    shepherd:
        build: ./shepherd
        image: oldwebtoday/shepherd

    chromium:
        build:
          context: ./browser-chromium-opengl
          args:
            CHROMIUM_VERSION: 65.0.3325.181-0ubuntu0.16.04.1 

        image: oldwebtoday/chromium-opengl:66

