version: '2'

services:
    shepherd:
        build: ./shepherd
        image: oldwebtoday/shepherd

    chromium:
        build:
          context: ./browser-chromium-opengl
          args:
            BROWSER_PACKAGE: chromium-browser_66.0.3359.139-0ubuntu0.16.04.3_amd64.deb

        image: oldwebtoday/chromium-opengl:66

